# Property description analysis

This notebook mostly exists to analysis the contents of the properties in the valuer general.

## Initialise database client

Initialise the database client

In [1]:
from lib.gnaf_db import GnafDb
from lib import notebook_constants as nc

gnaf = GnafDb.create()
gnaf_2 = GnafDb.create(nc.gnaf_dbconf_2, nc.gnaf_dbname_2)
gnaf.wait_till_running()
gnaf_2.wait_till_running()

## Create some helper functions

- `get_the_data`, this really just wraps calls to `pd.read_sql`, mostly boilerplate

In [2]:
import pandas as pd
from pprint import pprint
from sqlalchemy import text
from lib.nsw_vg.property_description import parse_property_description

def get_the_data(query, params=None, instance='gnaf_2'):
    engine = None
    if instance == 'gnaf_1':
        engine = gnaf.engine()
    elif instance == 'gnaf_2':
        engine = gnaf_2.engine()
    return pd.read_sql(text(query), engine, params=params)

## SQL Boilerplate

We'll use this to fetch different stuff from the database.

In [14]:
def most_properties(limit, offset):
    return get_the_data("""
      SELECT p.property_id as nsw_id,
             pd.property_description as desc,
             p.property_name as name,
             p.unit_number as unit,
             p.house_number as house,
             st.street_name as street,
             su.suburb_name as suburb,
             p.postcode,
             p.zone_code as zone,
             p.area,
             v.base_date,
             v.land_value
        FROM nsw_valuer_general.property_description pd
        JOIN nsw_valuer_general.property p ON p.property_id = pd.property_id
        JOIN nsw_valuer_general.street st ON p.street_id = st.street_id
        JOIN nsw_valuer_general.suburb su ON p.suburb_id = su.suburb_id
        JOIN (SELECT va.* FROM nsw_valuer_general.valuations va
               WHERE va.base_date =
                 (SELECT MAX(vb.base_date)
                    FROM nsw_valuer_general.valuations vb
                   WHERE va.property_id = vb.property_id)) v
          ON v.property_id = p.property_id
       WHERE pd.property_description !~ '^\d+/\d+(/\d+)?$' AND
             pd.property_description !~ '^,? ?Mineral (Claim|Lease) \d+[A-Z]?\s*$' AND
             pd.property_description !~ '^(\d+/\d+(/\d+)? )*(Mineral Claim \d+[R]? )*(Western Land Lease \d+ *)*$'
       ORDER BY land_value DESC, street, house, unit
      OFFSET   :offset
       LIMIT   :limit
    """, params={ 'offset': offset, 'limit': limit })

def description_containing(t, limit, offset):
    return get_the_data("""
      SELECT p.property_id as nsw_id,
             pd.property_description as desc,
             p.property_name as name,
             p.unit_number as unit,
             p.house_number as house,
             st.street_name as street,
             su.suburb_name as suburb,
             p.postcode,
             p.zone_code as zone,
             p.area,
             v.base_date,
             v.land_value
        FROM nsw_valuer_general.property_description pd
        JOIN nsw_valuer_general.property p ON p.property_id = pd.property_id
        JOIN nsw_valuer_general.street st ON p.street_id = st.street_id
        JOIN nsw_valuer_general.suburb su ON p.suburb_id = su.suburb_id
        JOIN (SELECT va.* FROM nsw_valuer_general.valuations va
               WHERE va.base_date =
                 (SELECT MAX(vb.base_date)
                    FROM nsw_valuer_general.valuations vb
                   WHERE va.property_id = vb.property_id)) v
          ON v.property_id = p.property_id
       WHERE pd.property_description ~ :text
       ORDER BY land_value DESC, street, house, unit
      OFFSET   :offset
       LIMIT   :limit
    """, params={ 'text': t, 'offset': offset, 'limit': limit })


def get_by_properties_id(property_ids):
    return get_the_data("""
      SELECT p.property_id as nsw_id,
             pd.property_description as desc,
             p.property_name as name,
             p.unit_number as unit,
             p.house_number as house,
             st.street_name as street,
             su.suburb_name as suburb,
             p.postcode,
             p.zone_code as zone,
             p.area,
             v.base_date,
             v.land_value
        FROM nsw_valuer_general.property p
        LEFT JOIN nsw_valuer_general.property_description pd ON p.property_id = pd.property_id
        JOIN nsw_valuer_general.street st ON p.street_id = st.street_id
        JOIN nsw_valuer_general.suburb su ON p.suburb_id = su.suburb_id
        LEFT JOIN nsw_valuer_general.source src ON p.source_id = src.source_id
        LEFT JOIN nsw_valuer_general.source_file sf ON src.source_file_id = sf.source_file_id
        JOIN (SELECT va.* FROM nsw_valuer_general.valuations va
               WHERE va.base_date =
                 (SELECT MAX(vb.base_date)
                    FROM nsw_valuer_general.valuations vb
                   WHERE va.property_id = vb.property_id)) v
          ON v.property_id = p.property_id
       WHERE p.property_id IN :pids
       ORDER BY p.property_id
    """, params={ "pids": property_ids })

def get_gnaf_address(limit, offset):
    return get_the_data("""
      SELECT 
          ad.address_detail_pid as gnaf_id,
          ad.legal_parcel_id,
          ad.building_name,
          CONCAT(ad.lot_number_prefix, ad.lot_number, ad.lot_number_suffix) as lot,
          CONCAT(ad.flat_number_prefix, ad.flat_number, ad.flat_number_suffix) as unit,
          CONCAT(COALESCE(ad.level_type_code || ' ', ''),
                 COALESCE(ad.level_number_prefix || '-', ''),
                 ad.level_number,
                 COALESCE('-' || ad.level_number_suffix, '')) as level,
          CONCAT(
            ad.number_first_prefix, ad.number_first, ad.number_first_suffix,
            COALESCE('-' || ad.number_last_prefix || ad.number_last || ad.number_last_suffix, '')
          ) as house,
          sl.street_name,
          l.locality_name,
          ad.postcode
        FROM gnaf.ADDRESS_DETAIL ad
        JOIN gnaf.LOCALITY l ON ad.locality_pid = l.locality_pid
        JOIN gnaf.STREET_LOCALITY sl ON ad.street_locality_pid = sl.street_locality_pid
        JOIN gnaf.STATE s ON l.state_pid = s.state_pid
       WHERE s.state_abbreviation = 'NSW'
         AND ad.legal_parcel_id IN (
          SELECT ad.legal_parcel_id FROM gnaf.ADDRESS_DETAIL ad
           GROUP BY ad.legal_parcel_id HAVING COUNT(*) > 1)
       ORDER BY ad.legal_parcel_id, street_name, house, level, unit
      OFFSET   :offset
       LIMIT   :limit
    """, params={ 'offset': offset, 'limit': limit })

## Introspect the property description

Here we are just seeing which property descriptions seem to contain content that is abit weird.

In [11]:
from lib.nsw_vg.property_description import parse_property_description

rows = most_properties(limit=100, offset=2400)
# rows = most_properties(limit=50, offset=200) # have not checked up to 1900

weird = []
for i, row in rows.iterrows():
    desc = rows.loc[i, 'desc']
    remaining, expanded = parse_property_description(desc)
    
    if remaining:
        pprint({
            'id': int(rows.loc[i, 'nsw_id']),
            'description': desc,
            'remaining': remaining,
            # 'expanded': expanded,
        })
        weird.append(desc)
pprint(weird)

display(rows.iloc[:50])
display(rows.iloc[50:])

{'description': '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, '
                '18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, '
                '33, 34, 35, 36, 37, 38, 39, 40, 41, 42, CP/SP36548 LOT 100 DP '
                '716204 (BEING LOTS 1/42 SP 36548)',
 'id': 854983,
 'remaining': 'LOT100DP716204(BEINGLOTS1/42SP36548)'}
{'description': '1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 14, 15, 16, 17, 18, 19, '
                '20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, '
                '35, 36, 37, CP/SP32905 38/SP32921 MARINA Permissive Occupancy '
                '1957/409',
 'id': 1628476,
 'remaining': 'MARINA/409'}
{'description': '1/502735 MSB LEASE', 'id': 2091862, 'remaining': 'MSBLEASE'}
{'description': '192/874868 Shared use - 37% NSW Maritime 30003573',
 'id': 4033553,
 'remaining': '-37%'}
['1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, '
 '22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, '
 '41, 42, CP/SP36548 LOT 100 DP 716204 (BEING LOTS 1/42 SP 36548)',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, '
 '24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, CP/SP32905 '
 '38/SP32921 MARINA Permissive Occupancy 1957/409',
 '1/502735 MSB LEASE',
 '192/874868 Shared use - 37% NSW Maritime 30003573']

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
0,3631113,PT 1/1169345,PIRRAMA PARK,None,20,PIRRAMA RD,PYRMONT,2009,RE1,12750.0,2023-01-07,24600000
1,3435051,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,60-82,PRINCES HWY,ST PETERS,2044,MU1,3985.0,2023-01-07,24600000
2,793651,"1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 16...",None,None,50,UPPER PITT ST,KIRRIBILLI,2061,R4,2892.0,2023-01-07,24600000
3,2102466,A/367302,None,None,46,VAUCLUSE RD,VAUCLUSE,2030,R2,1707.0,2023-01-07,24600000
4,2076344,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,17-23,WALLIS PDE,NORTH BONDI,2026,R3,2946.6,2023-01-07,24600000
5,4151551,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,697-701,PITTWATER RD,DEE WHY,2099,MU1,5276.0,2023-01-07,24594966
6,3315412,PT 38/1098588,None,None,50,BARROW RD,MOUNT ANNAN,2567,E4,310000.0,2023-01-07,24500000
7,3810429,"1/114218 1/180264 1, 2, 3, 4, 7, 8, 9, 10, 27,...",BEREMBED STATION,None,431,CARINGA RD,GRONG GRONG,2652,RU4,42803300.0,2023-01-07,24500000
8,728034,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,52,CHRISTIE ST,ST LEONARDS,2065,E2,4591.0,2023-01-07,24500000
9,1390904,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,11-13,CLARENCE ST,BURWOOD,2134,MU1,2379.0,2023-01-07,24500000
10,3414537,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,2-4,CUNNINGHAM ST,HAYMARKET,2000,SP5,907.4,2023-01-07,24500000
11,3942817,"15, 16, 20, 21, 22, 23, 24, 25, 26, 31/750420 ...",ROUNDHAY,None,None,CURRAGUNDI RD,WEEMELAH,2406,RU1,37770000.0,2023-01-07,24500000
12,4107244,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,3,FORESHORE BVD,WOOLOOWARE,2230,E1,42060.0,2023-01-07,24500000
13,4236046,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,1158,GOOLGUMBLA RD,MABINS WELL,2716,RU1,205265600.0,2023-01-07,24500000
14,2031844,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",GEORGIA APARTMENTS PROJECT,None,155-157,KENT ST,MILLERS POINT,2000,SP5,345.5,2023-01-07,24500000
15,4171155,"44, 45, 46/16554 2, 3/16979 1/235994 10/238154...",NOORONG STATION,None,40,NOORONG RD,NOORONG,2732,RU1,111951400.0,2023-01-07,24500000
16,2068304,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,41-47,OCEAN ST N,BONDI,2026,R4,2352.4,2023-01-07,24500000
17,4440642,"30/720260 1, 3, 4, 5/751201 1, 3, 26, 27, 28/7...",NIMMIE-CAIRA,None,3741,WAUGORAH RD,WAUGORAH,2711,RU1,345493100.0,2023-01-07,24500000
18,1911714,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",THE MOORINGS,None,24,WOLSELEY ST,DRUMMOYNE,2047,R3,3933.0,2023-01-07,24500000
19,2152086,"A, B/161650",None,None,244-258,YOUNG ST,WATERLOO,2017,MU1,3504.0,2023-01-07,24500000
20,3902446,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,795,BOTANY RD,ROSEBERY,2018,E3,6855.4,2023-01-07,24456541
21,3279431,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,50,AUBIN ST,NEUTRAL BAY,2089,R4,4070.0,2023-01-07,24400000
22,2109501,"1, 2, CP/SP46659",None,None,293,BOTANY RD,WATERLOO,2017,MU1,4321.0,2023-01-07,24400000
23,691829,"A/321567 B, C/322331 A, B/336206 1/504794 200,...",KMC PROPERTY,None,11-21,COWAN RD,ST IVES,2075,E1,14600.0,2023-01-07,24400000
24,2084115,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,54,DARLING POINT RD,DARLING POINT,2027,R3,2200.0,2023-01-07,24400000
25,3080175,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,1,DAY ST,CHATSWOOD,2067,MU1,21090.0,2023-01-07,24400000
26,2026113,1/84749 1/220638,None,None,372-394,ELIZABETH ST,SURRY HILLS,2010,MU1,1068.0,2023-01-07,24400000
27,4309581,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,1,GLEN ST,EASTWOOD,2122,MU1,5820.0,2023-01-07,24400000
28,854983,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,20,GREAT WESTERN HWY,PARRAMATTA,2150,MU1,2401.0,2023-01-07,24400000
29,3683749,"7, 9/580996 1/595487 4, 5, 7, 8, 9, 10, 11, 12...",CANARAI & INNISFAIL,None,1124,GURLEY CREEK RD,GURLEY,2398,RU1,33627420.0,2023-01-07,24400000
30,1332786,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,244,HORSLEY RD,MILPERRA,2214,IN2,25810.0,2023-01-07,24400000
31,1890961,X/408199,None,None,55,KENT RD,MASCOT,2020,E4,11950.0,2023-01-07,24400000
32,2133586,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,91,MACLEAY ST,POTTS POINT,2011,MU1,939.6,2023-01-07,24400000
33,788981,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,156,MILITARY RD,NEUTRAL BAY,2089,MU1,2159.0,2023-01-07,24400000
34,4026679,"2, 3/217768 1, 2/503522 8, 9, 11, 13, 15, 16, ...",GORIAN,None,1667,OLD BURREN RD,BURREN JUNCTION,2386,RU1,51389100.0,2023-01-07,24400000
35,2098592,"1, 2, 4, 5, 6, 8, 9, CP/SP11526 10, 11/SP49838",None,None,26,PACIFIC ST,WATSONS BAY,2030,R2,777.8,2023-01-07,24400000
36,3913763,"1, 2, 3/111385 1/134690 1/134812 1, 2/227342 1...",None,None,11214,RIVERINA HWY,SAVERNAKE,2646,RU1,27735000.0,2023-01-07,24400000
37,1628476,"1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 14, 15, 16,...",None,None,1-9,TARA ST,SYLVANIA,2224,R3,14790.0,2023-01-07,24400000
38,4177001,A/110159 NSW Maritime 30002586,None,None,58,WENTWORTH RD,VAUCLUSE,2030,R2,763.5,2023-01-07,24400000
39,745207,1/68097 12/88385 1/232595 3/549603 2/585060 1/...,None,None,4-16,WHISTLER ST,MANLY,2095,E1,2415.0,2023-01-07,24400000
40,2105024,"1, 2, CP/SP17372",None,None,58,WUNULLA RD,POINT PIPER,2027,R2,1037.0,2023-01-07,24400000
41,802732,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,29,YEO ST,NEUTRAL BAY,2089,R4,2787.0,2023-01-07,24400000
42,1932394,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",THE ITALIAN FORUM,None,23,NORTON ST,LEICHHARDT,2040,E1,NaN,2023-01-07,24367255
43,4541369,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,228,PITT ST,MERRYLANDS,2160,E2,5120.0,2023-01-07,24330000
44,3963388,PT 105/1188670,None,None,345,APPIN RD,APPIN,2560,RU2,2918110.0,2023-01-07,24300000
45,2108003,2/220255 1/515095 10/860297,ELIZABETH LODGE,None,46-48,BAYSWATER RD,RUSHCUTTERS BAY,2011,R1,1721.5,2023-01-07,24300000
46,2115670,"2, 3, 4, 5, 8, 9, 11, 12, 13, 14, 15, 16, 17, ...",THE GRID,None,72-78,BAYSWATER RD,RUSHCUTTERS BAY,2011,R1,1546.0,2023-01-07,24300000
47,3909589,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,17-25,BOUNDARY ST,ROSEVILLE,2069,R4,3489.0,2023-01-07,24300000
48,3821681,"9, 10, 11, 12, 13, 14/111908 1, 2/127306 3/188...",None,None,None,BYNEDALE RD,DAYSDALE,2646,RU1,32751100.0,2023-01-07,24300000
49,2082557,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,17-23,CECIL ST,PADDINGTON,2021,R3,4775.0,2023-01-07,24300000

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
50,4353817,"PT 10, PT 11, PT 17, 18, 19, 20, 59, 60, 61, P...",None,None,48,CHILDE ST,BYRON BAY,2481,P,4637.4,2023-01-07,24300000
51,1420570,"8/3248 1, 2, 3, 4, 5/14348 1, 2, 3, 4, 5, 6/14...",HAMPDEN PRIMARY SCHOOL,None,39-79,HAMPDEN RD,LAKEMBA,2195,R3,35490.0,2023-01-07,24300000
52,698306,"4, 5/1209 1/122431 1/122432 1/376563",SCHOOL ST IVES SOUTH,None,60-70,HORACE ST,ST IVES,2075,SP2,77810.0,2023-01-07,24300000
53,411049,"2/734883 2, PT 3, 4, 5, 6, 7/740683 1, 2, 3/78...",None,None,None,LACHLAN VALLEY WAY,GODFREYS CREEK,2586,RU1,55310000.0,2023-01-07,24300000
54,2091862,1/502735 MSB LEASE,None,None,16,LONGWORTH AVE,POINT PIPER,2027,R2,598.0,2023-01-07,24300000
55,2035628,"2, 3, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1...",PARK HOUSE,None,187-191,MACQUARIE ST,SYDNEY,2000,SP5,540.7,2023-01-07,24300000
56,2847293,78/6746 1/1028649,PACIFIC CLUB,None,29-30,OCEAN RD,PALM BEACH,2108,C4,2797.0,2023-01-07,24300000
57,792363,A/431687 10/660453 1/772247,None,None,583,PACIFIC HWY,ST LEONARDS,2065,MU1,1350.0,2023-01-07,24300000
58,708159,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",GORDON GARDENS,None,803-805,PACIFIC HWY,GORDON,2072,R4,6314.1,2023-01-07,24300000
59,1556906,"1, 2/812621",None,None,26-38,POWELL ST,HOMEBUSH,2140,MU1,5242.0,2023-01-07,24300000
60,3091398,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,75,STANLEY ST,CHATSWOOD,2067,R3,4141.0,2023-01-07,24300000
61,4421738,1/82359 1/185942 NSW Maritime 1590,None,1,69,YARRANABBE RD,DARLING POINT,2027,R3,1088.3,2023-01-07,24300000
62,4323246,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,666,PACIFIC HWY,CHATSWOOD,2067,E3,7973.0,2023-01-07,24251960
63,3042620,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",ADMIRALTY,None,1-9,ADMIRALTY DR,BREAKFAST POINT,2137,R3,4866.0,2023-01-07,24200000
64,859898,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,188-190,BALACLAVA RD,MARSFIELD,2122,R3,20930.0,2023-01-07,24200000
65,2053495,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,129-131,BRONTE RD,QUEENS PARK,2022,R3,2334.0,2023-01-07,24200000
66,4033553,192/874868 Shared use - 37% NSW Maritime 30003573,None,None,19A,COOLONG RD,VAUCLUSE,2030,R2,1039.6,2023-01-07,24200000
67,3234701,"CP/SP76583 3, 4, 5, 6, 7, 8, 9, 10/SP82883",None,None,1,GRANTHAM ST,POTTS POINT,2011,R1,873.1,2023-01-07,24200000
68,742974,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,5-17,HIGH ST,MANLY,2095,R1,3692.0,2023-01-07,24200000
69,4411220,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,680,KINGSWAY,MIRANDA,2228,R4,3960.0,2023-01-07,24200000
70,2035420,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",B M A BUILDING,None,135-137,MACQUARIE ST,SYDNEY,2000,SP5,581.0,2023-01-07,24200000
71,2567045,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",MOUNTAIN VIEW RETREAT RETIREMENT VILLAGE,None,37,MULGOA RD,PENRITH,2750,R4,28730.0,2023-01-07,24200000
72,4392311,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, CP/SP10...",None,None,636,NEW SOUTH HEAD RD,ROSE BAY,2029,E1,1528.0,2023-01-07,24200000
73,2899597,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",ATLAS APARTMENTS,None,11-15,POWER AVE,ALEXANDRIA,2015,MU1,6516.0,2023-01-07,24200000
74,2101891,2/235488 NSW Maritime 30002617,None,None,22A,TIVOLI AVE,ROSE BAY,2029,R2,885.6,2023-01-07,24200000
75,3966532,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",PARK RISE,None,21-37,WAITARA AVE,WAITARA,2077,R4,7605.0,2023-01-07,24200000
76,997195,3/7656 2/661014 4/958063,None,None,4-6,WARATAH RD,PALM BEACH,2108,C4,1403.7,2023-01-07,24200000
77,1904051,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,100,WILLIAM ST,FIVE DOCK,2046,R3,7724.0,2023-01-07,24200000
78,2971722,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,1-5,HUNTER ST,WATERLOO,2017,MU1,6923.0,2023-01-07,24116500
79,803835,PT 2/851525,None,None,15-19,AIRD ST,PARRAMATTA,2150,MU1,7349.0,2023-01-07,24100000
80,868068,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,164,CULLODEN RD,MARSFIELD,2122,R4,17430.0,2023-01-07,24100000
81,2083549,"1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15...",None,None,63,DARLING POINT RD,DARLING POINT,2027,R3,1941.8,2023-01-07,24100000
82,2121951,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,446-458,ELIZABETH ST,SURRY HILLS,2010,MU1,1318.0,2023-01-07,24100000
83,4368194,"1, 3, 4/112806 1/717594 5, 6, 7, 8, 11, 12, 51...",BENANI,None,378,EURABBA STATION LANE,BRIBBAREE,2594,RU1,33719700.0,2023-01-07,24100000
84,4065922,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,581-587,GARDENERS RD,MASCOT,2020,MU1,3261.5,2023-01-07,24100000
85,4141322,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,8,GERTRUDE ST,WOLLI CREEK,2205,MU1,3566.0,2023-01-07,24100000
86,4556073,"A, B, C, D/155524 1/241484 2, 3/256266 8/25938...",None,None,1915,GRASSMERE RD,CONDOBOLIN,2877,RU1,82077600.0,2023-01-07,24100000
87,1925402,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",STRATA SCHEME,None,26,GROVE ST,BIRCHGROVE,2041,R1,2422.0,2023-01-07,24100000
88,3955751,"17, 29, 33, 34, 39, 41, 47, 48, 49, 57/753332 ...",None,None,2334,JINGELLIC RD,WANTAGONG,2644,RU1,14903000.0,2023-01-07,24100000
89,4034124,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,5-15A,LAMOND DR,TURRAMURRA,2074,R4,5907.0,2023-01-07,24100000
90,2005196,PT 2/218800,None,None,236-242,MALABAR RD,SOUTH COOGEE,2034,R3,9011.0,2023-01-07,24100000
91,2134404,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,1,MARIAN ST,REDFERN,2016,MU1,2421.3,2023-01-07,24100000
92,3588766,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,26-30,MARIAN ST,KILLARA,2071,R4,3629.0,2023-01-07,24100000
93,4043502,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,17-23,MERRIWA ST,GORDON,2072,MU1,4320.0,2023-01-07,24100000
94,3491262,"1, 2, 3, 4, 5, 6, 7, 8, 9, CP/SP83070",None,None,1-3,ONSLOW AVE,ELIZABETH BAY,2011,R1,1274.0,2023-01-07,24100000
95,4460869,"100, 101/1215685",None,None,5-7,PARKES ST,PARRAMATTA,2150,MU1,1954.5,2023-01-07,24100000
96,4090557,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,116,PRINCES HWY,ARNCLIFFE,2205,MU1,7412.0,2023-01-07,24100000
97,1397121,A/303645,SHAFTSBURY COURT,None,75,SHAFTESBURY RD,BURWOOD,2134,MU1,2593.0,2023-01-07,24100000
98,4242012,"1, 2, 3, 4, 5, 6, 8, 10, 12, 13, 14, 15, 16, 1...",None,None,12,SHINFIELD AVE,ST IVES,2075,R4,3265.0,2023-01-07,24100000
99,714535,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,183,ST JOHNS AVE,GORDON,2072,C4,18350.0,2023-01-07,24100000

In [5]:
property_descriptions = get_by_properties_id((
    '570557', # 650/751743 Non-Irrigable Purchase 15
    '623846', # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, CP/SP10943
    '1878087', # B/100895 6, PT 20/755520 Enclosure Permit 510145
    '1878096', # 1, 2, 3/133592 99/755520 153/755529 Enclosure Permit 50192
    '1878175', # PT 1/628296 1/705069
    '2681801', # 98/1066289 Mineral Claim 30854 Western Land Lease 14457
    '2681809', # 26/1066289 Western Land Lease 14476 Western Land Lease 31572
    '2682051', # 44/1073508 253/1076808 Western Land Lease 16121
    '2682966', # 15/1073508 Mineral Claim 42522R Western Land Lease 14691
    '3625326', # Forest Permit OCP100015
    '3821010', # 1, 3, 4/366686 1, 2/435063 18, 70/755529 1, 2, 3, 4/1088131 1/1166347
    '3851809', # PT 6401/1257392 Railway Land Lease 221.0037
    '4483251', # 1, 2/199140 2/530749 82, 120, 181/756909 27, 57, 134, PT 135, 136, 137, 190, 202, PT 210, PT 211/756913
    '4483252', # PT 135, PT 210, PT 211/756913 Wind Farm AN614034	
    '3625277',
))

for i, row in property_descriptions.iterrows():
    desc = property_descriptions.loc[i, 'desc']
    remaining, expanded = parse_property_description(desc)
    pprint({
        'description': desc,
        'remaining': remaining,
        'expanded': expanded,
    })

property_descriptions

{'description': '650/751743 Non-Irrigable Purchase 15',
 'expanded': [NonIrrigablePurchase(id='15'),
              LandParcel(id='650/751743', part=False)],
 'remaining': ''}
{'description': '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, '
                '18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, CP/SP10943',
 'expanded': [LandParcel(id='1/SP10943', part=False),
              LandParcel(id='2/SP10943', part=False),
              LandParcel(id='3/SP10943', part=False),
              LandParcel(id='4/SP10943', part=False),
              LandParcel(id='5/SP10943', part=False),
              LandParcel(id='6/SP10943', part=False),
              LandParcel(id='7/SP10943', part=False),
              LandParcel(id='8/SP10943', part=False),
              LandParcel(id='9/SP10943', part=False),
              LandParcel(id='10/SP10943', part=False),
              LandParcel(id='11/SP10943', part=False),
              LandParcel(id='12/SP10943', part=False),
              LandParcel(id='13/SP10943', part=False),
              LandParcel(id='14/SP10943', part=False),
              LandParcel(id='15/SP10943', part=False),
              LandParcel(id='16/SP10943', part=False),
              LandParcel(id='17/SP10943', part=False),
              LandParcel(id='18/SP10943', part=False),
              LandParcel(id='19/SP10943', part=False),
              LandParcel(id='20/SP10943', part=False),
              LandParcel(id='21/SP10943', part=False),
              LandParcel(id='22/SP10943', part=False),
              LandParcel(id='23/SP10943', part=False),
              LandParcel(id='24/SP10943', part=False),
              LandParcel(id='25/SP10943', part=False),
              LandParcel(id='26/SP10943', part=False),
              LandParcel(id='27/SP10943', part=False),
              LandParcel(id='28/SP10943', part=False),
              LandParcel(id='29/SP10943', part=False),
              LandParcel(id='CP/SP10943', part=False)],
 'remaining': ''}
{'description': 'B/100895 6, PT 20/755520 Enclosure Permit 510145',
 'expanded': [EnclosurePermit(id='510145'),
              LandParcel(id='B/100895', part=False),
              LandParcel(id='6/755520', part=False),
              LandParcel(id='20/755520', part=True)],
 'remaining': ''}
{'description': '1, 2, 3/133592 99/755520 153/755529 Enclosure Permit 50192',
 'expanded': [EnclosurePermit(id='50192'),
              LandParcel(id='1/133592', part=False),
              LandParcel(id='2/133592', part=False),
              LandParcel(id='3/133592', part=False),
              LandParcel(id='99/755520', part=False),
              LandParcel(id='153/755529', part=False)],
 'remaining': ''}
{'description': 'PT 1/628296 1/705069',
 'expanded': [LandParcel(id='1/628296', part=True),
              LandParcel(id='1/705069', part=False)],
 'remaining': ''}
{'description': '98/1066289 Mineral Claim 30854 Western Land Lease 14457',
 'expanded': [MineralClaim(id='30854'),
              WesternLandLease(id='14457'),
              LandParcel(id='98/1066289', part=False)],
 'remaining': ''}
{'description': '26/1066289 Western Land Lease 14476 Western Land Lease 31572',
 'expanded': [WesternLandLease(id='14476'),
              WesternLandLease(id='31572'),
              LandParcel(id='26/1066289', part=False)],
 'remaining': ''}
{'description': '44/1073508 253/1076808 Western Land Lease 16121',
 'expanded': [WesternLandLease(id='16121'),
              LandParcel(id='44/1073508', part=False),
              LandParcel(id='253/1076808', part=False)],
 'remaining': ''}
{'description': '15/1073508 Mineral Claim 42522R Western Land Lease 14691',
 'expanded': [MineralClaim(id='42522R'),
              WesternLandLease(id='14691'),
              LandParcel(id='15/1073508', part=False)],
 'remaining': ''}
{'description': 'PT 98/721203 PT 93, PT 94, PT 96/755820 63, 64, 311, 312, '
                '313, 314, 358, 359, 360, 361/756502 2/1154215 PT 1/1154216 '
                '100/1166366 Licence 402630',
 'expanded': [CrownLandLicense(id='402630'),
              LandParcel(id='98/721203', part=True),
              LandParcel(id='93/755820', part=True),
              LandParcel(id='94/755820', part=True),
              LandParcel(id='96/755820', part=True),
              LandParcel(id='63/756502', part=False),
              LandParcel(id='64/756502', part=False),
              LandParcel(id='311/756502', part=False),
              LandParcel(id='312/756502', part=False),
              LandParcel(id='313/756502', part=False),
              LandParcel(id='314/756502', part=False),
              LandParcel(id='358/756502', part=False),
              LandParcel(id='359/756502', part=False),
              LandParcel(id='360/756502', part=False),
              LandParcel(id='361/756502', part=False),
              LandParcel(id='2/1154215', part=False),
              LandParcel(id='1/1154216', part=True),
              LandParcel(id='100/1166366', part=False)],
 'remaining': ''}
{'description': 'Forest Permit OCP100015',
 'expanded': [ForestPermit(id='OCP100015')],
 'remaining': ''}
{'description': '1, 3, 4/366686 1, 2/435063 18, 70/755529 1, 2, 3, 4/1088131 '
                '1/1166347',
 'expanded': [LandParcel(id='1/366686', part=False),
              LandParcel(id='3/366686', part=False),
              LandParcel(id='4/366686', part=False),
              LandParcel(id='1/435063', part=False),
              LandParcel(id='2/435063', part=False),
              LandParcel(id='18/755529', part=False),
              LandParcel(id='70/755529', part=False),
              LandParcel(id='1/1088131', part=False),
              LandParcel(id='2/1088131', part=False),
              LandParcel(id='3/1088131', part=False),
              LandParcel(id='4/1088131', part=False),
              LandParcel(id='1/1166347', part=False)],
 'remaining': ''}
{'description': 'PT 6401/1257392 Railway Land Lease 221.0037',
 'expanded': [RailwayLandLease(id='221.0037'),
              LandParcel(id='6401/1257392', part=True)],
 'remaining': ''}
{'description': '1, 2/199140 2/530749 82, 120, 181/756909 27, 57, 134, PT 135, '
                '136, 137, 190, 202, PT 210, PT 211/756913',
 'expanded': [LandParcel(id='1/199140', part=False),
              LandParcel(id='2/199140', part=False),
              LandParcel(id='2/530749', part=False),
              LandParcel(id='82/756909', part=False),
              LandParcel(id='120/756909', part=False),
              LandParcel(id='181/756909', part=False),
              LandParcel(id='27/756913', part=False),
              LandParcel(id='57/756913', part=False),
              LandParcel(id='134/756913', part=False),
              LandParcel(id='135/756913', part=True),
              LandParcel(id='136/756913', part=False),
              LandParcel(id='137/756913', part=False),
              LandParcel(id='190/756913', part=False),
              LandParcel(id='202/756913', part=False),
              LandParcel(id='210/756913', part=True),
              LandParcel(id='211/756913', part=True)],
 'remaining': ''}
{'description': 'PT 135, PT 210, PT 211/756913 Wind Farm AN614034',
 'expanded': [WindFarm(id='AN614034'),
              LandParcel(id='135/756913', part=True),
              LandParcel(id='210/756913', part=True),
              LandParcel(id='211/756913', part=True)],
 'remaining': ''}

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
0,570557,650/751743 Non-Irrigable Purchase 15,None,None,4,ABATTOIR RD,LAKE WYANGAN,2680,R5,3565.0,2023-01-07,439000
1,623846,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,1,AARON PL,WAHROONGA,2076,R2,9381.0,2023-01-07,7580000
2,1878087,"B/100895 6, PT 20/755520 Enclosure Permit 510145",4-D,None,971,4D RD,CAROONA,2343,RU1,478200.0,2023-01-07,438000
3,1878096,"1, 2, 3/133592 99/755520 153/755529 Enclosure ...",LYNDEN,None,758,4D RD,CAROONA,2343,RU1,3019900.0,2023-01-07,5320000
4,1878175,PT 1/628296 1/705069,YARRAMAN BLOCK,None,1055,4D RD,SPRING RIDGE,2343,RU1,2147000.0,2023-01-07,3790000
5,2681801,98/1066289 Mineral Claim 30854 Western Land Le...,None,None,None,14-10,LIGHTNING RIDGE,2834,SP1,2588.0,2023-01-07,3250
6,2681809,26/1066289 Western Land Lease 14476 Western La...,None,None,None,14-11,LIGHTNING RIDGE,2834,SP1,2455.0,2023-01-07,3250
7,2682051,44/1073508 253/1076808 Western Land Lease 16121,None,None,None,17-09,LIGHTNING RIDGE,2834,SP1,2535.0,2023-01-07,3250
8,2682966,15/1073508 Mineral Claim 42522R Western Land L...,None,None,None,16-09,LIGHTNING RIDGE,2834,SP1,2477.0,2023-01-07,3250
9,3625277,"PT 98/721203 PT 93, PT 94, PT 96/755820 63, 64...",TARWONGA & AUCHEN DHU,None,174,ABBOTTSLEY RD,WALCHA,2354,RU1,9442920.0,2023-01-07,6040000
10,3625326,Forest Permit OCP100015,None,None,None,306 BOOKOOKOORARA STATE FOREST,TENTERFIELD,2372,RU1,8090000.0,2023-01-07,104000
11,3821010,"1, 3, 4/366686 1, 2/435063 18, 70/755529 1, 2,...",WALLA PARK,None,383,4D RD,CAROONA,2343,RU1,4340000.0,2023-01-07,3250000
12,3851809,PT 6401/1257392 Railway Land Lease 221.0037,None,None,None,ABATTOIR RD,FORBES,2871,SP2,480.0,2023-01-07,3030
13,4483251,"1, 2/199140 2/530749 82, 120, 181/756909 27, 5...",None,None,250,AARONS PASS RD,PYRAMUL,2850,RU1,7540050.0,2023-01-07,1490000
14,4483252,"PT 135, PT 210, PT 211/756913 Wind Farm AN614034",WIND FARM AN614034,None,252,AARONS PASS RD,PYRAMUL,2850,RU1,74800.0,2023-01-07,505000

In [6]:
get_gnaf_address(limit=20, offset=60)

,gnaf_id,legal_parcel_id,building_name,lot,unit,level,house,street_name,locality_name,postcode
0,GANSW718138632,1000/1117715,PEPPERFIELD,,21,,8,WISEMAN,BOWRAL,2576
1,GANSW718138633,1000/1117715,PEPPERFIELD,,22,,8,WISEMAN,BOWRAL,2576
2,GANSW718138634,1000/1117715,PEPPERFIELD,,23,,8,WISEMAN,BOWRAL,2576
3,GANSW718127753,1000/1117715,PEPPERFIELD,,24,,8,WISEMAN,BOWRAL,2576
4,GANSW718138635,1000/1117715,PEPPERFIELD,,25,,8,WISEMAN,BOWRAL,2576
5,GANSW718138636,1000/1117715,PEPPERFIELD,,26,,8,WISEMAN,BOWRAL,2576
6,GANSW718138637,1000/1117715,PEPPERFIELD,,27,,8,WISEMAN,BOWRAL,2576
7,GANSW718138638,1000/1117715,PEPPERFIELD,,28,,8,WISEMAN,BOWRAL,2576
8,GANSW718138639,1000/1117715,PEPPERFIELD,,29,,8,WISEMAN,BOWRAL,2576
9,GANSW718127760,1000/1117715,PEPPERFIELD,,3,,8,WISEMAN,BOWRAL,2576
10,GANSW718138640,1000/1117715,PEPPERFIELD,,30,,8,WISEMAN,BOWRAL,2576
11,GANSW718138641,1000/1117715,PEPPERFIELD,,31,,8,WISEMAN,BOWRAL,2576
12,GANSW718138642,1000/1117715,PEPPERFIELD,,32,,8,WISEMAN,BOWRAL,2576
13,GANSW718138643,1000/1117715,PEPPERFIELD,,33,,8,WISEMAN,BOWRAL,2576
14,GANSW718127755,1000/1117715,PEPPERFIELD,,34,,8,WISEMAN,BOWRAL,2576
15,GANSW718138644,1000/1117715,PEPPERFIELD,,35,,8,WISEMAN,BOWRAL,2576
16,GANSW718127756,1000/1117715,PEPPERFIELD,,36,,8,WISEMAN,BOWRAL,2576
17,GANSW718127757,1000/1117715,PEPPERFIELD,,37,,8,WISEMAN,BOWRAL,2576
18,GANSW718127758,1000/1117715,PEPPERFIELD,,38,,8,WISEMAN,BOWRAL,2576
19,GANSW718127759,1000/1117715,PEPPERFIELD,,39,,8,WISEMAN,BOWRAL,2576

# Anonomlies

## Descriptions containing `;`

In [18]:
from lib.nsw_vg.property_description import parse_property_description

rows = description_containing(';', limit=30, offset=0)
# rows = most_properties(limit=50, offset=200) # have not checked up to 1900

weird = []
for i, row in rows.iterrows():
    desc = rows.loc[i, 'desc']
    print(int(rows.loc[i, 'nsw_id']), desc)
    # pprint({
    #     'id': int(rows.loc[i, 'nsw_id']),
    #     'description': desc,
    #     'remaining': remaining,
    #     # 'expanded': expanded,
    # })

display(rows.iloc[:])

3838002 42, PT 57, PT 58, PT 59, PT 60, PT 61/754940 and Pt Leard State Forest No.420 in Parish of Leard; and then about 1700 ha subsurface being Lots 3, pt 35, 55, Pts 58, 64, 65 110 DP 754924; Lots 32, pt 35, 39, 40, 41, 42 DP 754940; Lots 27, 70, 74, 75, Pts 68, 69, 71, 83 DP 754948; Lots 1-2 DP 510801; pt 1 DP 1157540; pt 1, lot 3 DP 1144479; lot 1 DP114793; pt 7001 DP94069. Coal Lease 375 Mining Lease 1701
3407923 122/42056 2/718634 2/733835 58, 69, 132/751078 1, 2/1022767 1, 4, 5/1080470 for grazing(crown land bounded by 105/751078, 1,2/1080470;parcel west of 96/751078) Licence 344585 Licence 405371
748784 252/531397 Council lease (34sqm. - STONE SEAWA;L, RECLAIMED LAND, BOATSHED, DECK T/SKID) SHARED USE NSW Maritime 30003836
3665826 1/787417 13, 14, 15/1225577 Mining Lease 1620 - Total area 365.2 ha (Surface 83.04ha,  Sub-surface 282.2 ha) within Part Lot 14 & Pt Lot 15/1225577& Lot 1 DP787417) ; Mining Lease 1662 - Surface area of 93.09 ha being part ML2 in Ph Tulcumba Co Nandewar & within pt Lot 14/1225577) Mineral Lease 1662 Mining Lease 1620
3599739 12/1161984  (part Wildlife Refuge No.362); Enclosure Permit 22427
4363908 7309/1169890 5997/1205342 6058/1205343 6871/1205344 3578/1205346 PART; and crown roads Licence 623573
970426 PT 7093/93909 AND NSW MARITIME LEASE SHOWN IN PLAN No WL2025; BEING THE SITE OF NORTHBRIDGE SAILING CLUB, RAMP, PONTOON, CONCRETE PILES AND CHAIN STAYS. PART LOT 7093 DP 93909 HAS AN UNSPECIFIED AREA.
2473913 1/1062221 (being at Tarana in two parts:- Pumphouse (2042.5 m2);  Reservoir 1/1062221 and Easement) Railway Land Lease 151311
4362972 PART; crown roads Licence 623573
1245733 PT 1/209581 PT 7321/1166558 Subsurface Area = 53.41ha; Surface Area = 12.25 ha Mining Lease 739

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
0,3838002,"42, PT 57, PT 58, PT 59, PT 60, PT 61/754940 a...",MAULES CREEK COLLIERY,None,None,TRANTHAM RD,BOGGABRI,2382,RU1,43861000.0,2023-01-07,488000000
1,3407923,"122/42056 2/718634 2/733835 58, 69, 132/751078...",None,None,None,MOUNT LINDESAY RD,LISTON,2372,RU1,7777000.0,2023-01-07,5100000
2,748784,252/531397 Council lease (34sqm. - STONE SEAWA...,None,None,37,SEAFORTH CRES,SEAFORTH,2092,C3,1200.0,2023-01-07,3460000
3,3665826,"1/787417 13, 14, 15/1225577 Mining Lease 1620 ...",ROCGLEN,None,2569,WEAN RD,WEAN,2382,RU1,5823000.0,2023-01-07,1800000
4,3599739,12/1161984 (part Wildlife Refuge No.362); Enc...,None,None,1092,PLAINS STATION RD,TABULAM,2469,RU1,669600.0,2023-01-07,810000
5,4363908,7309/1169890 5997/1205342 6058/1205343 6871/12...,None,None,None,NEW ENGLAND HWY,GLENCOE,2365,RU1,904200.0,2023-01-07,333000
6,970426,PT 7093/93909 AND NSW MARITIME LEASE SHOWN IN ...,None,None,None,SAILORS BAY RD,NORTHBRIDGE,2063,C2,700.0,2023-01-07,189000
7,2473913,1/1062221 (being at Tarana in two parts:- Pump...,None,None,None,SODWALLS RD,TARANA,2787,RU1,6898.5,2023-01-07,71500
8,4362972,PART; crown roads Licence 623573,None,None,None,MAYBOLE RD,BEN LOMOND,2365,RU1,185000.0,2023-01-07,68000
9,1245733,PT 1/209581 PT 7321/1166558 Subsurface Area = ...,MINE,None,None,DAROOBALGIE RD,FORBES,2871,RU1,122500.0,2023-01-07,27800