In [2]:
from lib.gnaf_db import GnafDb
from lib import notebook_constants as nc
from lib.remote_resources import StaticFileInitialiser
from lib.nsw_vg.data_discovery import LandValueDiscovery, WeeklySalePriceDiscovery

initialiser = StaticFileInitialiser.create()
land_value = LandValueDiscovery()
sale_price = WeeklySalePriceDiscovery()

sale_price_target = sale_price.get_latest()
land_value_target = land_value.get_latest()

if land_value_target:
    initialiser.add_target(land_value_target)
    
if sale_price_target:
    initialiser.add_target(sale_price_target)
    
initialiser.setup_dirs()
initialiser.fetch_remote_resources()

gnaf = GnafDb.create()
gnaf_2 = GnafDb.create(nc.gnaf_dbconf_2, nc.gnaf_dbname_2)
gnaf.wait_till_running()
gnaf_2.wait_till_running()

Checking gnaf-2020.zip
Checking non_abs_shape.zip
Checking cities.zip
Checking nswvg_lv_01_Sep_2024.zip
Checking nswvg_wps_02_Sep_2024.zip

In [2]:
import pandas as pd
from pprint import pprint
from sqlalchemy import text
from lib.nsw_vg.property_description import parse_property_description

def get_the_data(query, params=None, instance='gnaf_1'):
    engine = None
    if instance == 'gnaf_1':
        engine = gnaf.engine()
    elif instance == 'gnaf_2':
        engine = gnaf_2.engine()
    return pd.read_sql(text(query), engine, params=params)

In [3]:
rows = get_the_data("""
  SELECT p.property_id as nsw_id,
         pd.property_description as desc,
         p.property_name as name,
         p.unit_number as unit,
         p.house_number as house,
         st.street_name as street,
         su.suburb_name as suburb,
         p.postcode,
         p.zone_code as zone,
         p.area,
         v.base_date,
         v.land_value
    FROM nsw_valuer_general.property_description pd
    JOIN nsw_valuer_general.property p ON p.property_id = pd.property_id
    JOIN nsw_valuer_general.street st ON p.street_id = st.street_id
    JOIN nsw_valuer_general.suburb su ON p.suburb_id = su.suburb_id
    JOIN (SELECT va.* FROM nsw_valuer_general.valuations va
           WHERE va.base_date =
             (SELECT MAX(vb.base_date)
                FROM nsw_valuer_general.valuations vb
               WHERE va.property_id = vb.property_id)) v
      ON v.property_id = p.property_id
   WHERE pd.property_description ~ '^\d+/\d+(/\d+)?$'
   -- WHERE pd.property_description !~ '^\d+/\d+(/\d+)?$' AND
   --       pd.property_description !~ '^,? ?Mineral (Claim|Lease) \d+[A-Z]?\s*$' AND
   --       pd.property_description !~ '^(\d+/\d+(/\d+)? )*(Mineral Claim \d+[R]? )*(Western Land Lease \d+ *)*$'
   ORDER BY land_value DESC, street, house, unit
  OFFSET    0 -- 1900
   LIMIT   50
""")


weird = []
for i, row in rows.iterrows():
    desc = rows.loc[i, 'desc']
    remaining, expanded = parse_property_description(desc)
    
    if remaining:
        pprint({
            'description': desc,
            'remaining': remaining,
            'expanded': expanded,
        })
        weird.append(desc)
pprint(weird)

rows

[]

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
0,4496832,1/1290500,None,None,1,ALFRED ST,SYDNEY,2000,SP5,14230.0,2023-01-07,438875113
1,4544964,2/1276320,None,None,565,LUDDENHAM RD,LUDDENHAM,2745,MU,1875000.0,2023-01-07,425000000
2,4456225,1/1287712,None,None,1953-2109,ELIZABETH DR,BADGERYS CREEK,2555,ENT,2805000.0,2023-01-07,394000000
3,3623946,21/1171076,None,None,14-54,DENNISTOUN AVE,YENNORA,2161,E4,700330.0,2023-01-07,365000000
4,4544963,1/1276320,None,None,601,LUDDENHAM RD,LUDDENHAM,2745,MU,1006000.0,2023-01-07,363000000
5,4491385,3101/1282964,None,None,215,BADGERYS CREEK RD,BRADFIELD,2556,MU,1131000.0,2023-01-07,352000000
6,4348804,60/1107965,WILLANDRA VILLAGE,None,157,BALACLAVA RD,MACQUARIE PARK,2113,MU1,63920.0,2023-01-07,340000000
7,3791727,100/1190494,MACQUARIE SHOPPING CENTRE,None,197-223,HERRING RD,MACQUARIE PARK,2113,MU1,110700.0,2023-01-07,325000000
8,3819161,1/1182754,None,None,188,PITT ST,SYDNEY,2000,SP5,11860.0,2023-01-07,319000000
9,3169836,2/1073376,None,None,50,BRIDGE ST,SYDNEY,2000,SP5,5838.0,2023-01-07,318000000
10,4545607,170/1291883,CHIFLEY TOWER,None,2,CHIFLEY SQ,SYDNEY,2000,SP5,6438.0,2023-01-07,317000000
11,4523139,132/1297655,None,None,None,SANDSTONE CRES,MACQUARIE PARK,2113,MU1,55060.0,2023-01-07,308000000
12,3971166,213/1221076,COMMERCIAL TOWER 1,None,100,BARANGAROO AVE,BARANGAROO,2000,B4,30200.0,2023-01-07,305265614
13,3679936,10/1179388,None,None,138-196,BOURKE RD,ALEXANDRIA,2015,E3,143700.0,2023-01-07,299000000
14,3870533,201/1204948,TOWER 2,None,200,BARANGAROO AVE,BARANGAROO,2000,B4,26290.0,2023-01-07,266834048
15,3716196,104/836610,None,None,1,FARRER PL,SYDNEY,2000,SP5,30670.0,2023-01-07,257810861
16,4464097,200/1285691,None,None,106-228,ALDINGTON RD,KEMPS CREEK,2178,IN1,720900.0,2023-01-07,256000000
17,4534716,4/1288129,None,None,1,ELIZABETH ST,SYDNEY,2000,SP5,33020.0,2023-01-07,241517324
18,3488402,11/1144025,None,None,9,INTERCHANGE DR,EASTERN CREEK,2766,IN1,366600.0,2023-01-07,241000000
19,4201288,11/1251992,None,None,1-3,MILLNER AVE,HORSLEY PARK,2175,IN1,377600.0,2023-01-07,241000000
20,3723163,2/1186495,MILITARY LAND,None,None,HEATHCOTE RD,HOLSWORTHY,2173,SP2,26830000.0,2023-01-07,238000000
21,3971162,211/1217691,COMMERCIAL TOWER 3,None,300,BARANGAROO AVE,BARANGAROO,2000,B4,24600.0,2023-01-07,237992012
22,3520080,37/1150819,RANDWICK BARRACKS,None,373A,AVOCA ST,RANDWICK,2031,R1,273200.0,2023-01-07,234000000
23,2036321,1/598704,MLC CENTRE,None,25,MARTIN PL,SYDNEY,2000,SP5,7061.0,2023-01-07,230023669
24,4535118,603/1296368,None,None,None,BARANGAROO AVE,BARANGAROO,2000,B4,27770.0,2023-01-07,228746877
25,4447287,101/1287187,None,None,180,GEORGE ST,SYDNEY,2000,SP5,21020.0,2023-01-07,221021942
26,4323616,3/271278,None,None,None,HILL RD,WENTWORTH POINT,2127,R4,77240.0,2023-01-07,218000000
27,4336560,2/1268157,None,None,100,TALAVERA RD,MACQUARIE PARK,2113,MU1,13330.0,2023-01-07,214000000
28,3750239,200/1183399,AREA 8,None,None,PENRHYN RD,BANKSMEADOW,2019,SP1,452600.0,2023-01-07,208000000
29,2034989,53/787143,GATEWAY PLAZA,None,1,MACQUARIE PL,SYDNEY,2000,SP5,5173.0,2023-01-07,207000000
30,3750243,203/1183399,SITE 1,None,7-15,PENRHYN RD,BANKSMEADOW,2019,SP1,452000.0,2023-01-07,207000000
31,4496647,100/1287207,None,None,475,BADGERYS CREEK RD,BADGERYS CREEK,2555,ENT,1811000.0,2023-01-07,201000000
32,2563613,1/104958,None,None,706-752,MAMRE RD,KEMPS CREEK,2178,IN1,521000.0,2023-01-07,200000000
33,4534350,552/1279032,None,None,None,EASTERN CREEK DR,EASTERN CREEK,2766,IN1,719400.0,2023-01-07,198000000
34,3731053,2012/1183894,UNIVERSITY OF TECHNOLOGY,None,9-73,BROADWAY,ULTIMO,2007,MU1,27660.0,2023-01-07,197000000
35,3693062,50/1182618,SITE 12,None,36-42,FRIENDSHIP RD,PORT BOTANY,2036,SP1,392500.0,2023-01-07,196000000
36,4150689,100/1240519,AUSTRALIAN QUARANTINE STATION,None,60,WALLGROVE RD,EASTERN CREEK,2766,IN1,218700.0,2023-01-07,193000000
37,2036333,1/633736,COLONIAL STATE BANK,None,52-56,MARTIN PL,SYDNEY,2000,SP5,3558.0,2023-01-07,192000000
38,4496833,2/1290500,None,None,1,PITT ST,SYDNEY,2000,SP5,9667.0,2023-01-07,191707190
39,2038311,101/1011617,None,None,88,PHILLIP ST,SYDNEY,2000,SP5,2598.0,2023-01-07,187000000
40,2035938,1823/841390,PARLIAMENT HOUSE,None,6,MACQUARIE ST,SYDNEY,2000,SP5,10390.0,2023-01-07,186000000
41,4360018,12/1214642,None,None,10,CARRINGTON ST,SYDNEY,2000,SP5,19700.0,2023-01-07,184675115
42,4305563,1/1253429,None,None,175,LIVERPOOL ST,SYDNEY,2000,SP5,4303.0,2023-01-07,182000000
43,3435979,100/1126282,None,None,1,BLIGH ST,SYDNEY,2000,SP5,3317.0,2023-01-07,180000000
44,2035943,5/775888,SYDNEY OPERA HOUSE,None,2,CIRCULAR QY E,SYDNEY,2000,SP5,36060.0,2023-01-07,180000000
45,3785510,1/1183173,None,None,161,CASTLEREAGH ST,SYDNEY,2000,SP5,38060.0,2023-01-07,177683515
46,2038096,12/1048563,None,None,2-26,PARK ST,SYDNEY,2000,SP5,8087.0,2023-01-07,176123006
47,4210151,2/1247122,None,None,34,PHILLIP ST,PARRAMATTA,2150,MU1,13700.0,2023-01-07,172000000
48,2029541,1/839399,ABC BUILDING,None,654-700,HARRIS ST,ULTIMO,2007,MU1,11320.0,2023-01-07,171000000
49,3956735,12/1217641,None,None,15,CARTER ST,LIDCOMBE,2141,R4,45690.0,2023-01-07,170000000

In [4]:
rows = get_the_data("""
  SELECT p.property_id as nsw_id,
         pd.property_description as desc,
         p.property_name as name,
         p.unit_number as unit,
         p.house_number as house,
         st.street_name as street,
         su.suburb_name as suburb,
         p.postcode,
         p.zone_code as zone,
         p.area,
         v.base_date,
         v.land_value
    FROM nsw_valuer_general.property_description pd
    JOIN nsw_valuer_general.property p ON p.property_id = pd.property_id
    JOIN nsw_valuer_general.street st ON p.street_id = st.street_id
    JOIN nsw_valuer_general.suburb su ON p.suburb_id = su.suburb_id
    JOIN (SELECT va.* FROM nsw_valuer_general.valuations va
           WHERE va.base_date =
             (SELECT MAX(vb.base_date)
                FROM nsw_valuer_general.valuations vb
               WHERE va.property_id = vb.property_id)) v
      ON v.property_id = p.property_id
   WHERE pd.property_description !~ '^,? ?Mineral (Claim|Lease) \d+[A-Z]?\s*$' AND
         pd.property_description !~ '^,? ?Mineral (Claim|Lease) \d+[A-Z]?\s*$' AND
         pd.property_description !~ '^\d+/\d+(/\d+)?$' AND
         pd.property_description !~ '^(\d+/\d+(/\d+)? )*(Mineral Claim \d+[R]? )*(Western Land Lease \d+ *)*$'
   -- WHERE pd.property_description NOT ILIKE 'Mineral Claim %' AND
   --       pd.property_description NOT ILIKE 'Mineral Lease %' AND
   --       pd.property_description NOT ILIKE '% Western Land Lease %' AND
   --       pd.property_description NOT ILIKE '% Non-Irrigable Purchase %' AND
   --       pd.property_description NOT ILIKE '% Railway Land Lease %' AND
   --       p.zone_code NOT IN :ignored_zones
   ORDER BY street, house, unit
  OFFSET 150
   LIMIT 50
""", params={
    "ignored_zones": ('RU1', 'RU2', 'RU3', 'RU4', 'RU5', 'SP1', 'E1', 'E2', 'E3', 'E4', 'RE1'),    
})


for i, row in rows.iterrows():
    desc = rows.loc[i, 'desc']
    remaining, expanded = parse_property_description(desc)
    
    if remaining:
        pprint({
            'description': desc,
            'remaining': remaining,
            'expanded': expanded,
        })

rows

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
0,2229648,"1, 2, 3, 4, 5, 6, 7, CP/SP56627",None,None,14,ABBOTT RD,SEVEN HILLS,2147,E4,2314.0,2023-01-07,3680000
1,2869628,"1, 2, 3, 4, 5, 6, 7, 8, 9, CP/SP65830",None,None,2,ABBOTT RD,SEVEN HILLS,2147,E4,4271.0,2023-01-07,6600000
2,897378,"225, 226, 228, 229, 230/752038",None,None,225,ABBOTT RD,NORTH CURL CURL,2099,RE1,31990.0,2023-01-07,6270000
3,897407,B/391200,None,None,34A,ABBOTT RD,NORTH CURL CURL,2099,R2,1100.0,2023-01-07,2660000
4,897406,PT 56/20103,None,None,34B,ABBOTT RD,NORTH CURL CURL,2099,R2,116.1,2023-01-07,50800
5,2152374,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,36,ABBOTT RD,SEVEN HILLS,2147,E4,8031.0,2023-01-07,8830000
6,897408,A/391200,None,None,36,ABBOTT RD,NORTH CURL CURL,2099,R2,1100.0,2023-01-07,2660000
7,897379,"227, 373/752038",None,None,373,ABBOTT RD,NORTH CURL CURL,2099,RE1,13050.0,2023-01-07,2830000
8,2152350,"1, 2, 3, 4, 5, 6, 7, 8, 9, CP/SP51766 11, 12, ...",None,None,4,ABBOTT RD,SEVEN HILLS,2147,E4,4750.0,2023-01-07,7090000
9,949470,"1/88143 A, B/318869 723, 724, 725, 726, 727/75...",None,None,5,ABBOTT RD,ARTARMON,2064,SP2,5916.2,2023-01-07,12300000
10,897419,291A/386392,None,None,56,ABBOTT RD,NORTH CURL CURL,2099,R2,1612.0,2023-01-07,3010000
11,897420,291C/386392,None,None,58,ABBOTT RD,NORTH CURL CURL,2099,R2,796.7,2023-01-07,2620000
12,3171568,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,6,ABBOTT RD,SEVEN HILLS,2147,E4,10160.0,2023-01-07,14600000
13,3634972,7355/1167221 Crown Reserve R84882,HARBORD LAGOON AND RESERVE,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,30.0,2023-01-07,2750
14,897386,247/752038 Crown Reserve 84882,HARBORD LAGOON AND RESERVE,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,4199.0,2023-01-07,1130000
15,897377,"1, 2, 3, 4, 5, 6, 7/13257",PUBLIC PARK AND RECREATION,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,5160.0,2023-01-07,1420000
16,897382,"235, 236, 237, 238, 239/752038",BASKETT BALL COURTS,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,21440.0,2023-01-07,5190000
17,897387,"248, 249, 250/752038",SOCCER FIELDS,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,8574.0,2023-01-07,2300000
18,897380,"231, 232/752038",None,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,7689.0,2023-01-07,2000000
19,897388,"251, 252/752038 Crown Reserve 84882",HARBORD LAGOON AND RESERVE,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,6880.0,2023-01-07,1910000
20,897385,"243, 244, 245, 246/752038",SOCCER FIELDS,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,13630.0,2023-01-07,3680000
21,916698,"216, 217, 218, 219, 220/752038",ABBOTT ROAD SOFTBALL FIELDS,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,35370.0,2023-01-07,6080000
22,3336670,7114/1030407 Crown Reserve R87301,None,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,5934.0,2023-01-07,1380000
23,897390,2682/752038 Special Lease 76331,LAWN BOWLS CLUB,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE2,10620.0,2023-01-07,1700000
24,897389,PT 253/752038,PUBLIC PARK AND RECREATION,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,1518.0,2023-01-07,322000
25,897383,"240, 241/752038 Crown Reserve 84882",NETBALL COURTS,None,None,ABBOTT RD,NORTH CURL CURL,2099,RE1,9156.0,2023-01-07,2180000
26,2983829,23/1041913 Enclosure Permit 53282,None,None,115,ABBOTTS FALLS RD,WINGHAM,2429,RU1,598500.0,2023-01-07,780000
27,1789320,"3, 4, 34, 52/754454",None,None,256,ABBOTTS FALLS RD,WINGHAM,2429,RU1,865980.0,2023-01-07,2220000
28,2887598,"130, 132/754863",LAURISTON,None,237,ABBOTTS LANE,DELUNGRA,2403,RU1,1396000.0,2023-01-07,1410000
29,3965497,"259, 260, 261/754578 4/1213720",None,None,27,ABBOTTS LANE,GRENFELL,2810,RU1,41480.0,2023-01-07,328000
30,3432926,2/613693 1/1131447,None,None,321,ABBOTTS LANE,DELUNGRA,2403,RU1,1795000.0,2023-01-07,1850000
31,4019747,129/754863 1/1227020,None,None,417,ABBOTTS LANE,DELUNGRA,2403,RU1,1657490.0,2023-01-07,1620000
32,4368106,"253, 255, 256, 257, 258, 438/754578",None,None,78,ABBOTTS LANE,GRENFELL,2810,RU1,88070.0,2023-01-07,405000
33,4495050,"212, 213, 217, 218, 234, 235, 236, 237, 238, 2...",HAEREMAI,None,78,ABBOTTS LANE,GRENFELL,2810,RU1,219190.0,2023-01-07,585000
34,3625277,"PT 98/721203 PT 93, PT 94, PT 96/755820 63, 64...",TARWONGA & AUCHEN DHU,None,174,ABBOTTSLEY RD,WALCHA,2354,RU1,9442920.0,2023-01-07,6040000
35,4355027,"B/381236 44, 69, 70, 97, 100, 101, 102, 103, 1...",None,None,257,ABBOTTSLEY RD,WALCHA,2354,RU1,8515400.0,2023-01-07,7020000
36,4355026,"2/512960 31, 33, 37, 50/756476 117/756492 57, ...",None,None,64,ABBOTTSLEY RD,WALCHA,2354,RU1,7858170.0,2023-01-07,6470000
37,3640009,"PT 101/755820 53/756476 65, 104, 106, 107, 108...",None,None,None,ABBOTTSLEY RD,WALCHA,2354,RU1,10693550.0,2023-01-07,8730000
38,3673091,"5, 6, 7, 8, 9, 10, 26, 27, 28, 29, 30, 31, 37,...",DANICA,None,124,ABBOTTS RD,GLEN INNES,2370,RU1,2779900.0,2023-01-07,1410000
39,4494155,"51, 52/1834",None,None,124,ABBOTTS RD,GLEN INNES,2370,RU1,178390.0,2023-01-07,421000
40,4494153,50/1834 1/1231696,None,None,152,ABBOTTS RD,GLEN INNES,2370,RU1,88600.0,2023-01-07,347000
41,1775492,"2, 3/804612",None,None,163,ABBOTTS RD,BOOTAWA,2430,RU4,2594.2,2023-01-07,15600
42,1791663,"8/114723 3, 138/753217 7003/1000939 Licence 30...",None,None,165,ABBOTTS RD,DYERS CROSSING,2429,RU1,337240.0,2023-01-07,654000
43,4057547,1/571521 2/1231737,None,None,168,ABBOTTS RD,GLEN INNES,2370,RU1,25500.0,2023-01-07,260000
44,4398854,"26, 27, 28, 29, 96, 97, 98/756905",WILLOW GLEN,None,168,ABBOTTS RD,TAMBAROORA,2850,RU1,44470.0,2023-01-07,67200
45,1775345,1/253318 156/753152,None,None,172,ABBOTTS RD,BOOTAWA,2430,RU4,176000.0,2023-01-07,470000
46,1775396,3/561585 Enclosure Permit 103656,None,None,216,ABBOTTS RD,BOOTAWA,2430,RU4,178900.0,2023-01-07,492000
47,3503960,"1/872393 102/881792 1, 2/1141146",None,None,225,ABBOTTS RD,BOOTAWA,2430,RU4,238900.0,2023-01-07,748000
48,1775362,2/201331 Enclosure Permit 117248,None,None,246,ABBOTTS RD,BOOTAWA,2430,RU4,222200.0,2023-01-07,492000
49,1775308,"1/201331 14/753152 1, 2, 3/1085053 Enclosure P...",None,None,251,ABBOTTS RD,BOOTAWA,2430,RU4,918800.0,2023-01-07,1150000

In [5]:
get_the_data("""
  SELECT 
      ad.address_detail_pid as gnaf_id,
      ad.legal_parcel_id,
      ad.building_name,
      CONCAT(ad.lot_number_prefix, ad.lot_number, ad.lot_number_suffix) as lot,
      CONCAT(ad.flat_number_prefix, ad.flat_number, ad.flat_number_suffix) as unit,
      CONCAT(COALESCE(ad.level_type_code || ' ', ''),
             COALESCE(ad.level_number_prefix || '-', ''),
             ad.level_number,
             COALESCE('-' || ad.level_number_suffix, '')) as level,
      CONCAT(
        ad.number_first_prefix, ad.number_first, ad.number_first_suffix,
        COALESCE('-' || ad.number_last_prefix || ad.number_last || ad.number_last_suffix, '')
      ) as house,
      sl.street_name,
      l.locality_name,
      ad.postcode
    FROM gnaf.ADDRESS_DETAIL ad
    JOIN gnaf.LOCALITY l ON ad.locality_pid = l.locality_pid
    JOIN gnaf.STREET_LOCALITY sl ON ad.street_locality_pid = sl.street_locality_pid
    JOIN gnaf.STATE s ON l.state_pid = s.state_pid
   WHERE s.state_abbreviation = 'NSW'
     AND ad.legal_parcel_id IN (
      SELECT ad.legal_parcel_id FROM gnaf.ADDRESS_DETAIL ad
       GROUP BY ad.legal_parcel_id HAVING COUNT(*) > 1)
   ORDER BY ad.legal_parcel_id, street_name, house, level, unit
   LIMIT 20
  OFFSET 60
""")

,gnaf_id,legal_parcel_id,building_name,lot,unit,level,house,street_name,locality_name,postcode
0,GANSW718138632,1000/1117715,PEPPERFIELD,,21,,8,WISEMAN,BOWRAL,2576
1,GANSW718138633,1000/1117715,PEPPERFIELD,,22,,8,WISEMAN,BOWRAL,2576
2,GANSW718138634,1000/1117715,PEPPERFIELD,,23,,8,WISEMAN,BOWRAL,2576
3,GANSW718127753,1000/1117715,PEPPERFIELD,,24,,8,WISEMAN,BOWRAL,2576
4,GANSW718138635,1000/1117715,PEPPERFIELD,,25,,8,WISEMAN,BOWRAL,2576
5,GANSW718138636,1000/1117715,PEPPERFIELD,,26,,8,WISEMAN,BOWRAL,2576
6,GANSW718138637,1000/1117715,PEPPERFIELD,,27,,8,WISEMAN,BOWRAL,2576
7,GANSW718138638,1000/1117715,PEPPERFIELD,,28,,8,WISEMAN,BOWRAL,2576
8,GANSW718138639,1000/1117715,PEPPERFIELD,,29,,8,WISEMAN,BOWRAL,2576
9,GANSW718127760,1000/1117715,PEPPERFIELD,,3,,8,WISEMAN,BOWRAL,2576
10,GANSW718138640,1000/1117715,PEPPERFIELD,,30,,8,WISEMAN,BOWRAL,2576
11,GANSW718138641,1000/1117715,PEPPERFIELD,,31,,8,WISEMAN,BOWRAL,2576
12,GANSW718138642,1000/1117715,PEPPERFIELD,,32,,8,WISEMAN,BOWRAL,2576
13,GANSW718138643,1000/1117715,PEPPERFIELD,,33,,8,WISEMAN,BOWRAL,2576
14,GANSW718127755,1000/1117715,PEPPERFIELD,,34,,8,WISEMAN,BOWRAL,2576
15,GANSW718138644,1000/1117715,PEPPERFIELD,,35,,8,WISEMAN,BOWRAL,2576
16,GANSW718127756,1000/1117715,PEPPERFIELD,,36,,8,WISEMAN,BOWRAL,2576
17,GANSW718127757,1000/1117715,PEPPERFIELD,,37,,8,WISEMAN,BOWRAL,2576
18,GANSW718127758,1000/1117715,PEPPERFIELD,,38,,8,WISEMAN,BOWRAL,2576
19,GANSW718127759,1000/1117715,PEPPERFIELD,,39,,8,WISEMAN,BOWRAL,2576

In [6]:
property_descriptions = get_the_data("""
  SELECT p.property_id as nsw_id,
         pd.property_description as desc,
         -- src.source_file_position,
         -- sf.source_file_name,
         p.property_name as name,
         p.unit_number as unit,
         p.house_number as house,
         st.street_name as street,
         su.suburb_name as suburb,
         p.postcode,
         p.zone_code as zone,
         p.area,
         v.base_date,
         v.land_value
    FROM nsw_valuer_general.property p
    LEFT JOIN nsw_valuer_general.property_description pd ON p.property_id = pd.property_id
    JOIN nsw_valuer_general.street st ON p.street_id = st.street_id
    JOIN nsw_valuer_general.suburb su ON p.suburb_id = su.suburb_id
    LEFT JOIN nsw_valuer_general.source src ON p.source_id = src.source_id
    LEFT JOIN nsw_valuer_general.source_file sf ON src.source_file_id = sf.source_file_id
    JOIN (SELECT va.* FROM nsw_valuer_general.valuations va
           WHERE va.base_date =
             (SELECT MAX(vb.base_date)
                FROM nsw_valuer_general.valuations vb
               WHERE va.property_id = vb.property_id)) v
      ON v.property_id = p.property_id
   WHERE p.property_id IN :pids
   ORDER BY p.property_id
""", params={
    'pids': (
        '570557', # 650/751743 Non-Irrigable Purchase 15
        '623846', # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, CP/SP10943
        '1878087', # B/100895 6, PT 20/755520 Enclosure Permit 510145
        '1878096', # 1, 2, 3/133592 99/755520 153/755529 Enclosure Permit 50192
        '1878175', # PT 1/628296 1/705069
        '2681801', # 98/1066289 Mineral Claim 30854 Western Land Lease 14457
        '2681809', # 26/1066289 Western Land Lease 14476 Western Land Lease 31572
        '2682051', # 44/1073508 253/1076808 Western Land Lease 16121
        '2682966', # 15/1073508 Mineral Claim 42522R Western Land Lease 14691
        '3625326', # Forest Permit OCP100015
        '3821010', # 1, 3, 4/366686 1, 2/435063 18, 70/755529 1, 2, 3, 4/1088131 1/1166347
        '3851809', # PT 6401/1257392 Railway Land Lease 221.0037
        '4483251', # 1, 2/199140 2/530749 82, 120, 181/756909 27, 57, 134, PT 135, 136, 137, 190, 202, PT 210, PT 211/756913
        '4483252', # PT 135, PT 210, PT 211/756913 Wind Farm AN614034	
        '3625277',
    )
})

for i, row in property_descriptions.iterrows():
    desc = property_descriptions.loc[i, 'desc']
    remaining, expanded = parse_property_description(desc)
    pprint({
        'description': desc,
        'remaining': remaining,
        'expanded': expanded,
    })

property_descriptions

{'description': '650/751743 Non-Irrigable Purchase 15',
 'expanded': [NonIrrigablePurchase(id='15'),
              LandParcel(id='650/751743', part=False)],
 'remaining': ''}
{'description': '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, '
                '18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, CP/SP10943',
 'expanded': [LandParcel(id='1/SP10943', part=False),
              LandParcel(id='2/SP10943', part=False),
              LandParcel(id='3/SP10943', part=False),
              LandParcel(id='4/SP10943', part=False),
              LandParcel(id='5/SP10943', part=False),
              LandParcel(id='6/SP10943', part=False),
              LandParcel(id='7/SP10943', part=False),
              LandParcel(id='8/SP10943', part=False),
              LandParcel(id='9/SP10943', part=False),
              LandParcel(id='10/SP10943', part=False),
              LandParcel(id='11/SP10943', part=False),
              LandParcel(id='12/SP10943', part=False),
              LandParcel(id='13/SP10943', part=False),
              LandParcel(id='14/SP10943', part=False),
              LandParcel(id='15/SP10943', part=False),
              LandParcel(id='16/SP10943', part=False),
              LandParcel(id='17/SP10943', part=False),
              LandParcel(id='18/SP10943', part=False),
              LandParcel(id='19/SP10943', part=False),
              LandParcel(id='20/SP10943', part=False),
              LandParcel(id='21/SP10943', part=False),
              LandParcel(id='22/SP10943', part=False),
              LandParcel(id='23/SP10943', part=False),
              LandParcel(id='24/SP10943', part=False),
              LandParcel(id='25/SP10943', part=False),
              LandParcel(id='26/SP10943', part=False),
              LandParcel(id='27/SP10943', part=False),
              LandParcel(id='28/SP10943', part=False),
              LandParcel(id='29/SP10943', part=False),
              LandParcel(id='CP/SP10943', part=False)],
 'remaining': ''}
{'description': 'B/100895 6, PT 20/755520 Enclosure Permit 510145',
 'expanded': [EnclosurePermit(id='510145'),
              LandParcel(id='B/100895', part=False),
              LandParcel(id='6/755520', part=False),
              LandParcel(id='20/755520', part=True)],
 'remaining': ''}
{'description': '1, 2, 3/133592 99/755520 153/755529 Enclosure Permit 50192',
 'expanded': [EnclosurePermit(id='50192'),
              LandParcel(id='1/133592', part=False),
              LandParcel(id='2/133592', part=False),
              LandParcel(id='3/133592', part=False),
              LandParcel(id='99/755520', part=False),
              LandParcel(id='153/755529', part=False)],
 'remaining': ''}
{'description': 'PT 1/628296 1/705069',
 'expanded': [LandParcel(id='1/628296', part=True),
              LandParcel(id='1/705069', part=False)],
 'remaining': ''}
{'description': '98/1066289 Mineral Claim 30854 Western Land Lease 14457',
 'expanded': [MineralClaim(id='30854'),
              WesternLandLease(id='14457'),
              LandParcel(id='98/1066289', part=False)],
 'remaining': ''}
{'description': '26/1066289 Western Land Lease 14476 Western Land Lease 31572',
 'expanded': [WesternLandLease(id='14476'),
              WesternLandLease(id='31572'),
              LandParcel(id='26/1066289', part=False)],
 'remaining': ''}
{'description': '44/1073508 253/1076808 Western Land Lease 16121',
 'expanded': [WesternLandLease(id='16121'),
              LandParcel(id='44/1073508', part=False),
              LandParcel(id='253/1076808', part=False)],
 'remaining': ''}
{'description': '15/1073508 Mineral Claim 42522R Western Land Lease 14691',
 'expanded': [MineralClaim(id='42522R'),
              WesternLandLease(id='14691'),
              LandParcel(id='15/1073508', part=False)],
 'remaining': ''}
{'description': 'PT 98/721203 PT 93, PT 94, PT 96/755820 63, 64, 311, 312, '
                '313, 314, 358, 359, 360, 361/756502 2/1154215 PT 1/1154216 '
                '100/1166366 Licence 402630',
 'expanded': [CrownLandLicense(id='402630'),
              LandParcel(id='98/721203', part=True),
              LandParcel(id='93/755820', part=True),
              LandParcel(id='94/755820', part=True),
              LandParcel(id='96/755820', part=True),
              LandParcel(id='63/756502', part=False),
              LandParcel(id='64/756502', part=False),
              LandParcel(id='311/756502', part=False),
              LandParcel(id='312/756502', part=False),
              LandParcel(id='313/756502', part=False),
              LandParcel(id='314/756502', part=False),
              LandParcel(id='358/756502', part=False),
              LandParcel(id='359/756502', part=False),
              LandParcel(id='360/756502', part=False),
              LandParcel(id='361/756502', part=False),
              LandParcel(id='2/1154215', part=False),
              LandParcel(id='1/1154216', part=True),
              LandParcel(id='100/1166366', part=False)],
 'remaining': ''}
{'description': 'Forest Permit OCP100015',
 'expanded': [ForestPermit(id='OCP100015')],
 'remaining': ''}
{'description': '1, 3, 4/366686 1, 2/435063 18, 70/755529 1, 2, 3, 4/1088131 '
                '1/1166347',
 'expanded': [LandParcel(id='1/366686', part=False),
              LandParcel(id='3/366686', part=False),
              LandParcel(id='4/366686', part=False),
              LandParcel(id='1/435063', part=False),
              LandParcel(id='2/435063', part=False),
              LandParcel(id='18/755529', part=False),
              LandParcel(id='70/755529', part=False),
              LandParcel(id='1/1088131', part=False),
              LandParcel(id='2/1088131', part=False),
              LandParcel(id='3/1088131', part=False),
              LandParcel(id='4/1088131', part=False),
              LandParcel(id='1/1166347', part=False)],
 'remaining': ''}
{'description': 'PT 6401/1257392 Railway Land Lease 221.0037',
 'expanded': [RailwayLandLease(id='221.0037'),
              LandParcel(id='6401/1257392', part=True)],
 'remaining': ''}
{'description': '1, 2/199140 2/530749 82, 120, 181/756909 27, 57, 134, PT 135, '
                '136, 137, 190, 202, PT 210, PT 211/756913',
 'expanded': [LandParcel(id='1/199140', part=False),
              LandParcel(id='2/199140', part=False),
              LandParcel(id='2/530749', part=False),
              LandParcel(id='82/756909', part=False),
              LandParcel(id='120/756909', part=False),
              LandParcel(id='181/756909', part=False),
              LandParcel(id='27/756913', part=False),
              LandParcel(id='57/756913', part=False),
              LandParcel(id='134/756913', part=False),
              LandParcel(id='135/756913', part=True),
              LandParcel(id='136/756913', part=False),
              LandParcel(id='137/756913', part=False),
              LandParcel(id='190/756913', part=False),
              LandParcel(id='202/756913', part=False),
              LandParcel(id='210/756913', part=True),
              LandParcel(id='211/756913', part=True)],
 'remaining': ''}
{'description': 'PT 135, PT 210, PT 211/756913 Wind Farm AN614034',
 'expanded': [WindFarm(id='AN614034'),
              LandParcel(id='135/756913', part=True),
              LandParcel(id='210/756913', part=True),
              LandParcel(id='211/756913', part=True)],
 'remaining': ''}

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
0,570557,650/751743 Non-Irrigable Purchase 15,None,None,4,ABATTOIR RD,LAKE WYANGAN,2680,R5,3565.0,2023-01-07,439000
1,623846,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",None,None,1,AARON PL,WAHROONGA,2076,R2,9381.0,2023-01-07,7580000
2,1878087,"B/100895 6, PT 20/755520 Enclosure Permit 510145",4-D,None,971,4D RD,CAROONA,2343,RU1,478200.0,2023-01-07,438000
3,1878096,"1, 2, 3/133592 99/755520 153/755529 Enclosure ...",LYNDEN,None,758,4D RD,CAROONA,2343,RU1,3019900.0,2023-01-07,5320000
4,1878175,PT 1/628296 1/705069,YARRAMAN BLOCK,None,1055,4D RD,SPRING RIDGE,2343,RU1,2147000.0,2023-01-07,3790000
5,2681801,98/1066289 Mineral Claim 30854 Western Land Le...,None,None,None,14-10,LIGHTNING RIDGE,2834,SP1,2588.0,2023-01-07,3250
6,2681809,26/1066289 Western Land Lease 14476 Western La...,None,None,None,14-11,LIGHTNING RIDGE,2834,SP1,2455.0,2023-01-07,3250
7,2682051,44/1073508 253/1076808 Western Land Lease 16121,None,None,None,17-09,LIGHTNING RIDGE,2834,SP1,2535.0,2023-01-07,3250
8,2682966,15/1073508 Mineral Claim 42522R Western Land L...,None,None,None,16-09,LIGHTNING RIDGE,2834,SP1,2477.0,2023-01-07,3250
9,3625277,"PT 98/721203 PT 93, PT 94, PT 96/755820 63, 64...",TARWONGA & AUCHEN DHU,None,174,ABBOTTSLEY RD,WALCHA,2354,RU1,9442920.0,2023-01-07,6040000
10,3625326,Forest Permit OCP100015,None,None,None,306 BOOKOOKOORARA STATE FOREST,TENTERFIELD,2372,RU1,8090000.0,2023-01-07,104000
11,3821010,"1, 3, 4/366686 1, 2/435063 18, 70/755529 1, 2,...",WALLA PARK,None,383,4D RD,CAROONA,2343,RU1,4340000.0,2023-01-07,3250000
12,3851809,PT 6401/1257392 Railway Land Lease 221.0037,None,None,None,ABATTOIR RD,FORBES,2871,SP2,480.0,2023-01-07,3030
13,4483251,"1, 2/199140 2/530749 82, 120, 181/756909 27, 5...",None,None,250,AARONS PASS RD,PYRAMUL,2850,RU1,7540050.0,2023-01-07,1490000
14,4483252,"PT 135, PT 210, PT 211/756913 Wind Farm AN614034",WIND FARM AN614034,None,252,AARONS PASS RD,PYRAMUL,2850,RU1,74800.0,2023-01-07,505000

In [7]:
property_descriptions = get_the_data("""
  SELECT p.property_id as nsw_id,
         pd.property_description as desc,
         -- src.source_file_position,
         -- sf.source_file_name,
         p.property_name as name,
         p.unit_number as unit,
         p.house_number as house,
         st.street_name as street,
         su.suburb_name as suburb,
         p.postcode,
         p.zone_code as zone,
         p.area,
         v.base_date,
         v.land_value
    FROM nsw_valuer_general.property p
    LEFT JOIN nsw_valuer_general.property_description pd ON p.property_id = pd.property_id
    JOIN nsw_valuer_general.street st ON p.street_id = st.street_id
    JOIN nsw_valuer_general.suburb su ON p.suburb_id = su.suburb_id
    LEFT JOIN nsw_valuer_general.source src ON p.source_id = src.source_id
    LEFT JOIN nsw_valuer_general.source_file sf ON src.source_file_id = sf.source_file_id
    JOIN (SELECT va.* FROM nsw_valuer_general.valuations va
           WHERE va.base_date =
             (SELECT MAX(vb.base_date)
                FROM nsw_valuer_general.valuations vb
               WHERE va.property_id = vb.property_id)) v
      ON v.property_id = p.property_id
   WHERE p.property_id IN :pids
   ORDER BY p.property_id
""", params={
    'pids': (
        '570557', # 650/751743 Non-Irrigable Purchase 15
        # '623846', # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, CP/SP10943
        # '1878087', # B/100895 6, PT 20/755520 Enclosure Permit 510145
        # '1878096', # 1, 2, 3/133592 99/755520 153/755529 Enclosure Permit 50192
        # '1878175', # PT 1/628296 1/705069
        # '2681801', # 98/1066289 Mineral Claim 30854 Western Land Lease 14457
        # '2681809', # 26/1066289 Western Land Lease 14476 Western Land Lease 31572
        # '2682051', # 44/1073508 253/1076808 Western Land Lease 16121
        # '2682966', # 15/1073508 Mineral Claim 42522R Western Land Lease 14691
        # '3625326', # Forest Permit OCP100015
        # '3821010', # 1, 3, 4/366686 1, 2/435063 18, 70/755529 1, 2, 3, 4/1088131 1/1166347
        # '3851809', # PT 6401/1257392 Railway Land Lease 221.0037
        # '4483251', # 1, 2/199140 2/530749 82, 120, 181/756909 27, 57, 134, PT 135, 136, 137, 190, 202, PT 210, PT 211/756913
        # '4483252', # PT 135, PT 210, PT 211/756913 Wind Farm AN614034	
        '3625277',
    )
})

for i, row in property_descriptions.iterrows():
    desc = property_descriptions.loc[i, 'desc']
    remaining, expanded = parse_property_description(desc)
    pprint({
        'description': desc,
        'remaining': remaining,
        'expanded': expanded,
    })

property_descriptions

{'description': '650/751743 Non-Irrigable Purchase 15',
 'expanded': [NonIrrigablePurchase(id='15'),
              LandParcel(id='650/751743', part=False)],
 'remaining': ''}
{'description': 'PT 98/721203 PT 93, PT 94, PT 96/755820 63, 64, 311, 312, '
                '313, 314, 358, 359, 360, 361/756502 2/1154215 PT 1/1154216 '
                '100/1166366 Licence 402630',
 'expanded': [CrownLandLicense(id='402630'),
              LandParcel(id='98/721203', part=True),
              LandParcel(id='93/755820', part=True),
              LandParcel(id='94/755820', part=True),
              LandParcel(id='96/755820', part=True),
              LandParcel(id='63/756502', part=False),
              LandParcel(id='64/756502', part=False),
              LandParcel(id='311/756502', part=False),
              LandParcel(id='312/756502', part=False),
              LandParcel(id='313/756502', part=False),
              LandParcel(id='314/756502', part=False),
              LandParcel(id='358/756502', part=False),
              LandParcel(id='359/756502', part=False),
              LandParcel(id='360/756502', part=False),
              LandParcel(id='361/756502', part=False),
              LandParcel(id='2/1154215', part=False),
              LandParcel(id='1/1154216', part=True),
              LandParcel(id='100/1166366', part=False)],
 'remaining': ''}

,nsw_id,desc,name,unit,house,street,suburb,postcode,zone,area,base_date,land_value
0,570557,650/751743 Non-Irrigable Purchase 15,None,None,4,ABATTOIR RD,LAKE WYANGAN,2680,R5,3565.0,2023-01-07,439000
1,3625277,"PT 98/721203 PT 93, PT 94, PT 96/755820 63, 64...",TARWONGA & AUCHEN DHU,None,174,ABBOTTSLEY RD,WALCHA,2354,RU1,9442920.0,2023-01-07,6040000